version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: matt-stremio_server_1
      APP_PORT: 3000
    
  server:
    image: tsaridas/stremio-docker:latest
    user: "1000:1000"
    init: true
